/**
 * Private seller listing — photos under /public/sales/honda-cb650f-2013/.
 */

const IMAGE_COUNT = 11;

export const HONDA_CB650F_2013_IMAGE_URLS: string[] = Array.from({ length: IMAGE_COUNT }, (_, i) => {
  const n = String(i + 1).padStart(2, "0");
  return `/sales/honda-cb650f-2013/${n}.jpg`;
});

export const HONDA_CB650F_2013_SLUG = "2013-honda-cb650f-black-gold";

export const hondaCb650f2013Description = [
  "🏍️ Honda CB650F 2013 — Black & Gold Custom Build | 🇬🇧 UK Foreign Owner | Fully Serviced",
  "30,000 km · Full Service History · Green Book in Owner's Name · Foreign UK Owner",
  "",
  "Selling my Honda CB650F — a bike I've owned and cared for with genuine pride. As a UK expat living in Bangkok, I have high standards when it comes to maintenance and presentation, and this bike reflects that. Everything has been done properly and on time, no shortcuts taken.",
  "",
  "🇬🇧 FOREIGN (UK) OWNER:",
  "• British owner with high standards of care and maintenance",
  "• Green book (เล่มทะเบียน) is registered in my name — clean, straightforward transfer",
  "• Full paper trail available for serious buyers",
  "",
  "🔧 FULL SERVICE JUST COMPLETED:",
  "• Engine oil change",
  "• Fork oil change",
  "• Spark plug change",
  "• Air filter change",
  "• Complete full service done — ride away with total confidence",
  "",
  "⚙️ UPGRADES & MODIFICATIONS:",
  "• Gold aftermarket wheels — striking contrast against the blacked-out bodywork",
  "• Carbon fibre dash panel",
  "• Carbon fibre tank cover",
  "• Crash protectors fitted",
  "• Full aftermarket exhaust system",
  "• Aftermarket seat cover",
  "",
  "🛞 TYRES:",
  "• Pirelli Angel GT — premium sport-touring rubber, excellent grip and mileage left",
  "",
  "📋 DOCUMENTATION:",
  "• Full service history",
  "• Green book in seller's (foreign UK owner's) name — hassle-free transfer",
  "",
  "This is a genuine, well-loved bike being sold by someone who takes pride in what they ride. No hidden issues, no deferred maintenance. Everything is as described.",
  "Serious buyers only. Viewings welcome in Bangkok.",
  "📞 Message to discuss price and arrange viewing.",
  "",
  "--------------------------------------",
  "",
  "🏍️ Honda CB650F ปี 2013 — สีดำล้อทองแต่งสวย | 🇬🇧 เจ้าของชาวต่างชาติ (อังกฤษ) | เซอร์วิสครบ",
  "30,000 กม. · ประวัติซ่อมบำรุงครบ · เล่มทะเบียนในชื่อเจ้าของ · เจ้าของชาวอังกฤษ",
  "",
  "ขาย Honda CB650F รถที่ผมดูแลรักษาด้วยความภาคภูมิใจมาโดยตลอด ในฐานะชาวอังกฤษที่อาศัยอยู่ในกรุงเทพฯ ผมมีมาตรฐานสูงในเรื่องการบำรุงรักษาและความสะอาดของรถ ทุกอย่างทำอย่างถูกต้องและตรงเวลา ไม่มีการละเลยหรือชะลอการซ่อมบำรุง",
  "",
  "🇬🇧 เจ้าของชาวต่างชาติ (อังกฤษ):",
  "• เจ้าของชาวอังกฤษ มาตรฐานการดูแลสูง ใส่ใจทุกรายละเอียด",
  "• เล่มทะเบียนอยู่ในชื่อผู้ขาย — โอนสะดวก ไม่ยุ่งยาก",
  "• มีเอกสารประวัติการซ่อมบำรุงครบถ้วนให้ตรวจสอบ",
  "",
  "🔧 เพิ่งทำเซอร์วิสใหม่ทั้งหมด:",
  "• เปลี่ยนน้ำมันเครื่องใหม่",
  "• เปลี่ยนน้ำมันโช้คหน้าใหม่",
  "• เปลี่ยนหัวเทียนใหม่",
  "• เปลี่ยนกรองอากาศใหม่",
  "• เซอร์วิสครบทุกรายการ — ขับได้ทันทีอย่างมั่นใจ",
  "",
  "⚙️ อุปกรณ์แต่งและการปรับแต่ง:",
  "• ล้อทอง (aftermarket) — ตัดกับสีดำของตัวรถได้อย่างโดดเด่น",
  "• ฝาครอบแผงหน้าปัด คาร์บอนไฟเบอร์",
  "• ฝาครอบถังน้ำมัน คาร์บอนไฟเบอร์",
  "• ยางกันกระแทก (crash protectors)",
  "• ท่อไอเสีย full system (aftermarket)",
  "• เบาะ aftermarket",
  "",
  "🛞 ยาง:",
  "• Pirelli Angel GT — ยางสปอร์ตทัวร์ริ่งพรีเมียม จับถนนดี ดอกยางยังเหลือมาก",
  "",
  "📋 เอกสาร:",
  "• ประวัติการซ่อมบำรุงครบถ้วน",
  "• เล่มทะเบียนในชื่อผู้ขาย (เจ้าของชาวอังกฤษ) — โอนได้ทันที",
  "",
  "รถคันนี้ดูแลมาด้วยความรักและความภาคภูมิใจ ไม่มีปัญหาซ่อนเร้น ไม่มีการชะลอการซ่อมบำรุง ทุกอย่างตรงตามที่ระบุ",
  "รับนัดดูรถได้ที่กรุงเทพฯ สำหรับผู้สนใจจริงเท่านั้น",
  "📞 ทักมาสอบถามราคาและนัดดูรถได้เลย",
].join("\n");

export const hondaCb650f2013Specifications: Record<string, string> = {
  Make: "Honda",
  Model: "CB650F",
  Year: "2013",
  Mileage: "30,000 km",
  Build: "Black & gold custom",
  Transmission: "Manual",
  Tyres: "Pirelli Angel GT",
  Owner: "UK expat (private seller)",
  "Green book": "In seller's name (per listing)",
  Price: "On application — contact seller",
};
