/**
 * Facebook recommendations for Siam EZ (public page).
 * Wording matches customer posts where provided; Thai text kept as written on Facebook.
 */

import type { SocialTestimonial } from "@/content/social-testimonials";

export const FACEBOOK_TESTIMONIALS: SocialTestimonial[] = [
  {
    id: "facebook-oak-soe-khant",
    platform: "facebook",
    service: "Staff & service",
    author: "Oak Soe Khant",
    quote: "Great Service Amazing Staff!!",
    stars: 5,
  },
  {
    id: "facebook-thanwa-issara",
    platform: "facebook",
    service: "Communication",
    author: "Thanwa Issara",
    quote: "great communication skills. 10/10. Very happy.",
    stars: 5,
  },
  {
    id: "facebook-kaung-min-khant",
    platform: "facebook",
    service: "General",
    author: "Kaung Min Khant",
    quote: "Easy To talk w Staff..Highly recommend",
    stars: 5,
  },
  {
    id: "facebook-jed-gabriel-posadas",
    platform: "facebook",
    service: "Staff & guidance",
    author: "Jed Gabriel Posadas",
    quote: "Friendly staff and clear instructions! highly recommend Siam EZ.",
    stars: 5,
  },
  {
    id: "facebook-alan-worsley",
    platform: "facebook",
    service: "General",
    author: "Alan Worsley",
    quote: "Great service! Thank you 10/10 🙂",
    stars: 5,
  },
  {
    id: "facebook-nishant-ramteke",
    platform: "facebook",
    service: "Process speed",
    author: "Nishant Ramteke",
    quote: "Simple, easy and fast process hundred percent recommend 👍",
    stars: 5,
  },
  {
    id: "facebook-george-kamran",
    platform: "facebook",
    service: "General",
    author: "George Kamran",
    quote:
      "Amazing hassle free service. Process so smooth. Siam EZ team made it super easy. I recommend Siam EZ services for smooth process. Thank you Siam EZ",
    stars: 5,
  },
  {
    id: "facebook-kodoku-nomi",
    platform: "facebook",
    service: "Step-by-step updates",
    author: "Kodoku Nomi",
    quote: "บริการดี รายงานทุกขั้นตอนให้ทราบระหว่างการดำเนินงาน",
    stars: 5,
  },
  {
    id: "facebook-janny-jans",
    platform: "facebook",
    service: "Trust & courtesy",
    author: "Janny Jans",
    quote: "แนะนำเลยค่ะ สุภาพใจดีเชื่อถือได้ค่ะ",
    stars: 5,
  },
  {
    id: "facebook-nittaya-mongkolpiyathana",
    platform: "facebook",
    service: "Safety & reliability",
    author: "Nittaya Mongkolpiyathana",
    quote: "บริการดีมาก คุยง่าย เชื่อถือได้ ปลอดภัยติดต่อด้วยแล้วสบายใจ แนะนำเจ้านี้เลยค่ะ",
    stars: 5,
  },
  {
    id: "facebook-pa-parichat",
    platform: "facebook",
    service: "Friendly service",
    author: "Pa Parichat",
    quote: "คุยง่าย เป็นกันเองมากจ้า แนะนำเลยจ้า",
    stars: 5,
  },
  {
    id: "facebook-armando-azores",
    platform: "facebook",
    service: "Vehicle name change",
    author: "Armando Azores",
    quote:
      "Guys are working really great. Solved my car name change problem within a couple of hours. Sunday sent the documents per Whatsapp, everything prepared, Monday everything successfully completed within 3 hours at the Chatuchak department of road Transportation center. And all these with just a 2 month tourist visa! Thank you, Guys! 😱🍷🍷",
    stars: 5,
  },
  {
    id: "facebook-tanapat-kamsuk",
    platform: "facebook",
    service: "Speed & friendliness",
    author: "Tanapat Kamsuk",
    quote: "บริการดี เป็นกันเองครับ บริการเร็วมาก",
    stars: 5,
  },
  {
    id: "facebook-pachara-angkharuengrattana",
    platform: "facebook",
    service: "General",
    author: "Pachara Angkharuengrattana",
    quote: "บริการดีมากครับ Good service!!",
    stars: 5,
  },
  {
    id: "facebook-nutchanon-ruengwicha",
    platform: "facebook",
    service: "Quality & service",
    author: "Nutchanon Ruengwicha",
    quote: "คุณภาพ100%ครับ บริการดี คุยง่าย เป็นกันเองครับ",
    stars: 5,
  },
  {
    id: "facebook-ben-zaborszky",
    platform: "facebook",
    service: "Reliability",
    author: "Ben Zaborszky",
    quote: "very good and reliable service",
    stars: 5,
  },
  {
    id: "facebook-jason-phillip-baker",
    platform: "facebook",
    service: "Bangkok support",
    author: "Jason Phillip Baker",
    quote:
      "If you are looking for help in Bangkok, Siam EZ is the best choice! They make difficult things very easy and fast.",
    stars: 5,
  },
  {
    id: "facebook-jessica-jane-sankey",
    platform: "facebook",
    service: "Languages & range",
    author: "Jessica Jane Sankey",
    quote:
      "Excellent service!! I found Siam EZ super helpful. Next time I need something I'll be in touch. They're reliable and fast and friendly and offer a wide range of services. They speak Thai and English and Japanese. Thanks so much! 🙏✨",
    stars: 5,
  },
  {
    id: "facebook-komkit-jaratwichakorn",
    platform: "facebook",
    service: "Buying & selling",
    author: "Komkit Jaratwichakorn",
    quote: "100% เลยครับซื้อ-ขายง่าย คุยง่ายเป็นกันเอง🥰🥰🥰",
    stars: 5,
  },
  {
    id: "facebook-radchapol-toadkunakron",
    platform: "facebook",
    service: "General",
    author: "Radchapol Toadkunakron",
    quote: "100% เลยครับ",
    stars: 5,
  },
  {
    id: "facebook-wirat-reuannoot",
    platform: "facebook",
    service: "Value & friendliness",
    author: "Wirat Reuannoot",
    quote: "บริการประทับใจ เป็นกันเอง ราคาไม่แพง",
    stars: 5,
  },
  {
    id: "facebook-kinoko-penguin-house",
    platform: "facebook",
    service: "Value & friendliness",
    author: "คิโนะโกะ ณ.บ้านเพนกวิน",
    quote: "บริการประทับใจ เป็นกันเอง ราคาไม่แพง",
    stars: 5,
  },
  {
    id: "facebook-kingphodam-return",
    platform: "facebook",
    service: "Quality recommendation",
    author: "Kingphodam Return",
    quote: "สบายใจมีคุณภาพ100%แนะนำเลยค่ะ",
    stars: 5,
  },
  {
    id: "facebook-martin-bkk",
    platform: "facebook",
    service: "Motorbike / onsite help",
    author: "Martin Bkk",
    quote:
      "My motorbike battery died this morning, I got no response from others repair shops, but Siam EZ replied in minutes. The technician came fast (within 2 hours), spoke good English, and fixed it in 5 mins flat. Excellent service — highly recommended! I will use their services in the future.",
    stars: 5,
  },
  {
    id: "facebook-cholasit-klinrot",
    platform: "facebook",
    service: "Trust & comfort",
    author: "Cholasit Klinrot",
    quote: "คุยง่าย เป็นกันเอง ไว้ใจได้เลยครับ ทำด้วยแล้วสบายใจสุดๆ",
    stars: 5,
  },
  {
    id: "facebook-pinai-laohawirote",
    platform: "facebook",
    service: "Punctuality",
    author: "Pinai Laohawirote",
    quote: "บริการดี ตรงเวลา แนะนำเลยครับ",
    stars: 5,
  },
  {
    id: "facebook-andrew-harkness-tindukasiri",
    platform: "facebook",
    service: "Speed & staff",
    author: "Andrew Harkness Tindukasiri",
    quote: "I highly recommend this service very fast and efficient. The staff are very helpful and kind",
    stars: 5,
  },
  {
    id: "facebook-lolexz-shidou",
    platform: "facebook",
    service: "Range of services",
    author: "Lolexz Shidou",
    quote:
      "Is about time someone launch this type of company with varieties of great services ! ! ! Well done guys !",
    stars: 5,
  },
];
