const en = {
  brand: "SiamEZ Office Directory",
  subtitle: "Find the right government office, then call or open the map.",
  searchPlaceholder: "Office, service, province, phone, or keyword",
  search: "Search",
  clear: "Clear filters",
  filters: "Filters",
  province: "Province",
  district: "District",
  category: "Category",
  service: "Service",
  area: "Area",
  all: "All",
  bangkok: "Bangkok",
  otherProvinces: "Other provinces",
  status: "Verification",
  sort: "Sort",
  sortUpdated: "Recently updated",
  sortVerified: "Recently verified",
  sortName: "Name",
  results: "{count} offices",
  noResults: "No offices match this search.",
  noResultsHint: "Try a province, a shorter name, or clear the filters. Services appear only after they are attached to an office.",
  favorites: "Favorites",
  recent: "Recently viewed",
  updated: "Recently updated",
  browseCategory: "Browse by category",
  browseProvince: "Browse by province",
  suggest: "Suggest an office",
  manage: "Manage directory",
  open: "Open",
  call: "Call",
  maps: "Google Maps",
  copyPhone: "Copy phone",
  copyAddress: "Copy address",
  website: "Website",
  share: "Share",
  copied: "Copied",
  saveFavorite: "Save",
  savedFavorite: "Saved",
  hours: "Opening hours",
  services: "Services at this office",
  documents: "Documents commonly required",
  appointment: "Appointments",
  internal: "SiamEZ notes",
  verifiedOn: "Last verified",
  notVerified: "Not verified yet",
  report: "Report incorrect information",
  correct: "Suggest a correction",
  source: "Source",
  contact: "Contact",
  address: "Address",
  morePhones: "Other numbers",
  noPhone: "No telephone number recorded",
  noAddress: "No street address recorded",
  noCoordinates: "Coordinates have not been recorded. The map button searches the saved address or office name.",
  mapTitle: "Locations with coordinates",
  mapEmpty: "None of these offices have coordinates yet.",
  mapNeedFilter: "Choose a province or search before loading the map.",
  mapUnavailable: "Map preview is unavailable.",
  starterNote: "Starter records leave unknown contact details blank. They are not verified.",
  accessDeniedTitle: "This directory is for SiamEZ staff",
  accessDeniedBody:
    "Sign in with a staff account, or ask an administrator to verify your freelancer profile and grant directory access.",
  portal: "Back to my account",
  signIn: "Sign in",
  signInToSave: "Sign in to save offices you use often.",
  suggestStaffOnly: "Office suggestions are sent by SiamEZ staff. Anyone can search and open the directory.",
  prev: "Previous",
  next: "Next",
  page: "Page {page} of {pages}",
  yes: "Yes",
  no: "No",
  unknown: "Not recorded",
  walkIns: "Walk-ins",
  appointmentRequired: "Appointment required",
  lunch: "Lunch break",
  holidays: "Public holidays",
  operatingDays: "Operating days",
  parking: "Parking",
  counter: "Counter and building",
  tips: "Tips for this office",
  procedure: "Procedural notes",
  links: "Government links",
  booking: "Booking",
  reliability: "Reliability",
  archived: "Archived",
  view: "View",
  list: "List",
  grid: "Grid",
  map: "Map",
  regions: {
    bangkok: "Bangkok",
    central: "Central",
    east: "East",
    north: "North",
    northeast: "Northeast",
    west: "West",
    south: "South",
  },
  statuses: {
    verified: "Verified",
    needs_verification: "Needs verification",
    unverified: "Unverified",
    temporarily_closed: "Temporarily closed",
    permanently_closed: "Permanently closed",
  },
  reportFields: {
    phone: "Phone number",
    address: "Address",
    hours: "Opening hours",
    services: "Services",
    closed: "Office closed",
    other: "Something else",
  },
  explanation: "What is wrong?",
  sendReport: "Send report",
  suggestedValue: "Suggested correction",
  sendCorrection: "Submit correction",
  suggestLead: "Suggestions are reviewed before they change the directory.",
  nameEn: "Name in English",
  nameTh: "Name in Thai",
  notes: "Notes",
  submitSuggestion: "Submit suggestion",
  emptyFavorites: "You have not saved any offices yet.",
  emptyRecent: "Offices you open will show up here.",
  adminTitle: "Directory administration",
  newOffice: "New office",
  editOffice: "Edit office",
  save: "Save office",
  archive: "Archive",
  restore: "Restore",
  archiveConfirm: "Archive this office? It will disappear from search until it is restored.",
  restoreConfirm: "Restore this office to the directory?",
  import: "Import CSV",
  export: "Export CSV",
  template: "Download template",
  taxonomy: "Categories and services",
  access: "Freelancer access",
  settings: "Verification settings",
  reports: "Reports",
  submissions: "Suggestions",
  stale: "Needs a verification check",
  includeArchived: "Include archived",
  archivedOnly: "Archived only",
  reminder: "Flag records that have not been verified for this many days.",
  reminderSave: "Save reminder",
  grant: "Grant access",
  revoke: "Revoke access",
  loadStarter: "Add missing starter records",
  loadStarterHelp: "Adds missing category, service, and office shells. It does not overwrite offices you have edited.",
  importHelp:
    "Use the template. Separate lists with |. Leave unknown phones, addresses, hours, and coordinates blank. Imports are never marked verified.",
  updateExisting: "Update existing offices that match the slug",
  preview: "Preview import",
  commit: "Import valid rows",
  imported: "Imported",
  skipped: "Skipped",
  rejected: "Rejected",
  approve: "Approve",
  reject: "Reject",
  reviewNotes: "Review notes",
  noPending: "Nothing waiting for review.",
  saved: "Saved.",
  requiredHint: "Only the name and province are required. Leave unknown fields blank.",
  keywords: "Keywords",
  keywordsHint: "Separate with commas. Use locality names such as Pattaya.",
  parent: "Parent organization",
  branch: "Branch",
  postal: "Postal code",
  latitude: "Latitude",
  longitude: "Longitude",
  mapsUrl: "Google Maps URL",
  extraMaps: "Other map URLs",
  email: "Email",
  facebook: "Facebook",
  phones: "Additional phone numbers",
  contactNotes: "Contact notes",
  serviceNotes: "Service notes",
  method: "How it was checked",
  sourceUrl: "Source URL",
  sourceNotes: "Source notes",
  slug: "Slug",
  active: "Active",
  sortOrder: "Sort order",
  description: "Description",
  add: "Add",
  retireConfirm: "Remove this item? If it is in use, it will be deactivated instead of deleted.",
  staffAlways: "Staff and administrators can open the directory while their account is active. Deactivate the user to remove that access.",
  freelancerRule: "Freelancers need a verified profile and an explicit grant. Revoke access here when someone leaves.",
  openQueue: "Open reports",
  pendingQueue: "Pending suggestions",
  audit: "Recent changes",
  closedDays: "Closed",
  breakStart: "Break from",
  breakEnd: "Break to",
  from: "Opens",
  to: "Closes",
  days: {
    mon: "Monday",
    tue: "Tuesday",
    wed: "Wednesday",
    thu: "Thursday",
    fri: "Friday",
    sat: "Saturday",
    sun: "Sunday",
  },
};

export type DirectoryCopy = typeof en;

const th: DirectoryCopy = {
  brand: "สมุดรายชื่อหน่วยงาน SiamEZ",
  subtitle: "ค้นหาหน่วยงานที่ถูกต้อง แล้วโทรหรือเปิดแผนที่",
  searchPlaceholder: "ชื่อหน่วยงาน บริการ จังหวัด เบอร์โทร หรือคำค้น",
  search: "ค้นหา",
  clear: "ล้างตัวกรอง",
  filters: "ตัวกรอง",
  province: "จังหวัด",
  district: "อำเภอ/เขต",
  category: "หมวด",
  service: "บริการ",
  area: "พื้นที่",
  all: "ทั้งหมด",
  bangkok: "กรุงเทพมหานคร",
  otherProvinces: "ต่างจังหวัด",
  status: "สถานะการตรวจสอบ",
  sort: "เรียง",
  sortUpdated: "อัปเดตล่าสุด",
  sortVerified: "ตรวจสอบล่าสุด",
  sortName: "ชื่อ",
  results: "{count} หน่วยงาน",
  noResults: "ไม่พบหน่วยงานที่ตรงกับการค้นหา",
  noResultsHint: "ลองค้นด้วยจังหวัดหรือชื่อที่สั้นลง หรือล้างตัวกรอง บริการจะแสดงเมื่อมีการผูกกับหน่วยงานแล้วเท่านั้น",
  favorites: "รายการโปรด",
  recent: "เปิดดูล่าสุด",
  updated: "อัปเดตล่าสุด",
  browseCategory: "เลือกตามหมวด",
  browseProvince: "เลือกตามจังหวัด",
  suggest: "เสนอหน่วยงาน",
  manage: "จัดการสมุดรายชื่อ",
  open: "เปิด",
  call: "โทร",
  maps: "Google Maps",
  copyPhone: "คัดลอกเบอร์",
  copyAddress: "คัดลอกที่อยู่",
  website: "เว็บไซต์",
  share: "แชร์",
  copied: "คัดลอกแล้ว",
  saveFavorite: "บันทึก",
  savedFavorite: "บันทึกแล้ว",
  hours: "เวลาทำการ",
  services: "บริการของหน่วยงานนี้",
  documents: "เอกสารที่มักต้องใช้",
  appointment: "การนัดหมาย",
  internal: "บันทึกสำหรับทีม SiamEZ",
  verifiedOn: "ตรวจสอบล่าสุด",
  notVerified: "ยังไม่ได้ตรวจสอบ",
  report: "แจ้งข้อมูลไม่ถูกต้อง",
  correct: "เสนอการแก้ไข",
  source: "แหล่งข้อมูล",
  contact: "การติดต่อ",
  address: "ที่อยู่",
  morePhones: "เบอร์อื่น",
  noPhone: "ยังไม่มีเบอร์โทร",
  noAddress: "ยังไม่มีที่อยู่",
  noCoordinates: "ยังไม่มีพิกัด ปุ่มแผนที่จะค้นจากที่อยู่หรือชื่อหน่วยงานที่บันทึกไว้",
  mapTitle: "ตำแหน่งที่มีพิกัด",
  mapEmpty: "หน่วยงานเหล่านี้ยังไม่มีพิกัด",
  mapNeedFilter: "เลือกจังหวัดหรือค้นหาก่อน จึงจะโหลดแผนที่",
  mapUnavailable: "ไม่สามารถแสดงแผนที่ได้",
  starterNote: "ข้อมูลเริ่มต้นเว้นช่องที่ยังไม่ทราบไว้ และยังไม่ถือว่าตรวจสอบแล้ว",
  accessDeniedTitle: "สมุดรายชื่อนี้สำหรับทีม SiamEZ",
  accessDeniedBody: "เข้าสู่ระบบด้วยบัญชีพนักงาน หรือให้ผู้ดูแลยืนยันโปรไฟล์ฟรีแลนซ์และเปิดสิทธิ์ให้",
  portal: "กลับไปบัญชีของฉัน",
  signIn: "เข้าสู่ระบบ",
  signInToSave: "เข้าสู่ระบบเพื่อบันทึกหน่วยงานที่ใช้บ่อย",
  suggestStaffOnly: "การแนะนำหน่วยงานส่งได้โดยพนักงาน SiamEZ ทุกคนค้นหาและเปิดสมุดรายชื่อได้",
  prev: "ก่อนหน้า",
  next: "ถัดไป",
  page: "หน้า {page} จาก {pages}",
  yes: "ใช่",
  no: "ไม่ใช่",
  unknown: "ยังไม่บันทึก",
  walkIns: "วอล์กอิน",
  appointmentRequired: "ต้องนัดหมาย",
  lunch: "พักเที่ยง",
  holidays: "วันหยุดนักขัตฤกษ์",
  operatingDays: "วันที่เปิด",
  parking: "ที่จอดรถ",
  counter: "อาคารและเคาน์เตอร์",
  tips: "คำแนะนำสำหรับหน่วยงานนี้",
  procedure: "ขั้นตอนที่ควรรู้",
  links: "ลิงก์หน่วยงาน",
  booking: "การจองคิว",
  reliability: "ความน่าเชื่อถือ",
  archived: "เก็บถาวร",
  view: "ดู",
  list: "รายการ",
  grid: "การ์ด",
  map: "แผนที่",
  regions: {
    bangkok: "กรุงเทพมหานคร",
    central: "ภาคกลาง",
    east: "ภาคตะวันออก",
    north: "ภาคเหนือ",
    northeast: "ภาคตะวันออกเฉียงเหนือ",
    west: "ภาคตะวันตก",
    south: "ภาคใต้",
  },
  statuses: {
    verified: "ตรวจสอบแล้ว",
    needs_verification: "ต้องตรวจสอบ",
    unverified: "ยังไม่ตรวจสอบ",
    temporarily_closed: "ปิดชั่วคราว",
    permanently_closed: "ปิดถาวร",
  },
  reportFields: {
    phone: "เบอร์โทร",
    address: "ที่อยู่",
    hours: "เวลาทำการ",
    services: "บริการ",
    closed: "หน่วยงานปิด",
    other: "อื่น ๆ",
  },
  explanation: "ข้อมูลส่วนไหนไม่ถูกต้อง",
  sendReport: "ส่งรายงาน",
  suggestedValue: "ข้อมูลที่เสนอให้แก้",
  sendCorrection: "ส่งการแก้ไข",
  suggestLead: "ข้อเสนอจะถูกตรวจก่อนจึงจะเปลี่ยนข้อมูลในสมุดรายชื่อ",
  nameEn: "ชื่อภาษาอังกฤษ",
  nameTh: "ชื่อภาษาไทย",
  notes: "หมายเหตุ",
  submitSuggestion: "ส่งข้อเสนอ",
  emptyFavorites: "คุณยังไม่ได้บันทึกหน่วยงาน",
  emptyRecent: "หน่วยงานที่คุณเปิดจะแสดงที่นี่",
  adminTitle: "จัดการสมุดรายชื่อ",
  newOffice: "เพิ่มหน่วยงาน",
  editOffice: "แก้ไขหน่วยงาน",
  save: "บันทึก",
  archive: "เก็บถาวร",
  restore: "นำกลับมา",
  archiveConfirm: "เก็บถาวรหน่วยงานนี้หรือไม่ จะไม่แสดงในการค้นหาจนกว่าจะนำกลับมา",
  restoreConfirm: "นำหน่วยงานนี้กลับเข้าสมุดรายชื่อหรือไม่",
  import: "นำเข้า CSV",
  export: "ส่งออก CSV",
  template: "ดาวน์โหลดเทมเพลต",
  taxonomy: "หมวดและบริการ",
  access: "สิทธิ์ฟรีแลนซ์",
  settings: "การตรวจสอบข้อมูล",
  reports: "รายงานข้อมูลผิด",
  submissions: "ข้อเสนอ",
  stale: "ถึงรอบต้องตรวจสอบ",
  includeArchived: "รวมรายการที่เก็บถาวร",
  archivedOnly: "เฉพาะที่เก็บถาวร",
  reminder: "ทำเครื่องหมายรายการที่ไม่ได้ตรวจสอบนานเกินจำนวนวันนี้",
  reminderSave: "บันทึกระยะเวลา",
  grant: "ให้สิทธิ์",
  revoke: "เพิกถอน",
  loadStarter: "เพิ่มข้อมูลเริ่มต้นที่ยังไม่มี",
  loadStarterHelp: "เพิ่มหมวด บริการ และหน่วยงานตั้งต้นที่ยังไม่มี และจะไม่เขียนทับรายการที่แก้ไขแล้ว",
  importHelp: "ใช้เทมเพลต คั่นรายการด้วย | เว้นเบอร์ ที่อยู่ เวลา และพิกัดที่ยังไม่ทราบ ข้อมูลนำเข้าจะไม่ถูกทำเครื่องหมายว่าตรวจสอบแล้ว",
  updateExisting: "อัปเดตรายการเดิมที่รหัสตรงกัน",
  preview: "ดูก่อนนำเข้า",
  commit: "นำเข้าแถวที่ถูกต้อง",
  imported: "นำเข้าแล้ว",
  skipped: "ข้าม",
  rejected: "ไม่ผ่าน",
  approve: "อนุมัติ",
  reject: "ปฏิเสธ",
  reviewNotes: "บันทึกการตรวจ",
  noPending: "ไม่มีรายการรอตรวจ",
  saved: "บันทึกแล้ว",
  requiredHint: "จำเป็นเฉพาะชื่อและจังหวัด ช่องที่ไม่ทราบให้เว้นว่าง",
  keywords: "คำค้น",
  keywordsHint: "คั่นด้วยจุลภาค เช่น พัทยา",
  parent: "หน่วยงานต้นสังกัด",
  branch: "สาขา",
  postal: "รหัสไปรษณีย์",
  latitude: "ละติจูด",
  longitude: "ลองจิจูด",
  mapsUrl: "ลิงก์ Google Maps",
  extraMaps: "ลิงก์แผนที่อื่น",
  email: "อีเมล",
  facebook: "เฟซบุ๊ก",
  phones: "เบอร์โทรเพิ่มเติม",
  contactNotes: "หมายเหตุการติดต่อ",
  serviceNotes: "หมายเหตุบริการ",
  method: "วิธีที่ใช้ตรวจสอบ",
  sourceUrl: "URL แหล่งข้อมูล",
  sourceNotes: "หมายเหตุแหล่งข้อมูล",
  slug: "รหัสอ้างอิง",
  active: "ใช้งาน",
  sortOrder: "ลำดับ",
  description: "คำอธิบาย",
  add: "เพิ่ม",
  retireConfirm: "นำรายการนี้ออกหรือไม่ ถ้ามีการใช้งานอยู่ ระบบจะปิดการใช้งานแทนการลบ",
  staffAlways: "พนักงานและผู้ดูแลเข้าสมุดรายชื่อได้ตราบใดที่บัญชียังใช้งานอยู่ ปิดบัญชีเพื่อระงับสิทธิ์",
  freelancerRule: "ฟรีแลนซ์ต้องผ่านการยืนยันและได้รับสิทธิ์ชัดเจน เพิกถอนที่นี่เมื่อพ้นสภาพ",
  openQueue: "รายงานที่ยังเปิด",
  pendingQueue: "ข้อเสนอที่รอตรวจ",
  audit: "การเปลี่ยนแปลงล่าสุด",
  closedDays: "ปิด",
  breakStart: "พักตั้งแต่",
  breakEnd: "พักถึง",
  from: "เปิด",
  to: "ปิด",
  days: {
    mon: "จันทร์",
    tue: "อังคาร",
    wed: "พุธ",
    thu: "พฤหัสบดี",
    fri: "ศุกร์",
    sat: "เสาร์",
    sun: "อาทิตย์",
  },
};

export function getDirectoryCopy(locale: string): DirectoryCopy {
  return locale === "th" ? th : en;
}

export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ""));
}
